<?php

namespace App\Filament\Resources;

use App\Filament\Resources\DataPokokResource\Pages;
use App\Filament\Resources\DataPokokResource\RelationManagers;
use App\Models\DataPokok;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;
use App\Filament\Exports\DataPokokExporter;
use Filament\Tables\Actions\ExportAction;

class DataPokokResource extends Resource
{
    protected static ?string $model = DataPokok::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('Nama')
                    ->maxLength(255),
                Forms\Components\TextInput::make('Pangkat')
                    ->numeric(),
                Forms\Components\TextInput::make('PangkatTituler')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KelompokDPP')
                    ->numeric(),
                Forms\Components\TextInput::make('AsalMasukan')
                    ->numeric(),
                Forms\Components\DateTimePicker::make('TMTTNI'),
                Forms\Components\DateTimePicker::make('TMTPenyesuaian'),
                Forms\Components\TextInput::make('SatJuruBayar')
                    ->maxLength(255),
                Forms\Components\DateTimePicker::make('TanggalLahir'),
                Forms\Components\TextInput::make('JenisKelamin')
                    ->numeric(),
                Forms\Components\TextInput::make('StatusKawin')
                    ->numeric(),
                Forms\Components\TextInput::make('JumlahAnak')
                    ->numeric(),
                Forms\Components\TextInput::make('JumlahTanggungan')
                    ->numeric(),
                Forms\Components\TextInput::make('StatPenghasilan')
                    ->numeric(),
                Forms\Components\TextInput::make('Korps')
                    ->numeric(),
                Forms\Components\TextInput::make('UnitOrganisasi')
                    ->numeric(),
                Forms\Components\TextInput::make('Kotama')
                    ->numeric(),
                Forms\Components\TextInput::make('StatJabatan')
                    ->numeric(),
                Forms\Components\TextInput::make('JenisJabatan')
                    ->numeric(),
                Forms\Components\TextInput::make('EselonJabatan')
                    ->numeric(),
                Forms\Components\TextInput::make('JnsJab2')
                    ->numeric(),
                Forms\Components\TextInput::make('EseJab2')
                    ->numeric(),
                Forms\Components\TextInput::make('NamaJabatan')
                    ->maxLength(255),
                Forms\Components\DateTimePicker::make('TMTJabatan'),
                Forms\Components\TextInput::make('Skorsing')
                    ->numeric(),
                Forms\Components\TextInput::make('Kotji')
                    ->numeric(),
                Forms\Components\TextInput::make('GantiRugi')
                    ->numeric(),
                Forms\Components\TextInput::make('SewaRumah')
                    ->numeric(),
                Forms\Components\TextInput::make('TunPeralihan')
                    ->numeric(),
                Forms\Components\TextInput::make('BulanWarakawuri')
                    ->numeric(),
                Forms\Components\TextInput::make('SatOrganik')
                    ->maxLength(255),
                Forms\Components\TextInput::make('Pekas')
                    ->maxLength(255),
                Forms\Components\TextInput::make('Satker')
                    ->maxLength(255),
                Forms\Components\DateTimePicker::make('TanggalBuat'),
                Forms\Components\DateTimePicker::make('TanggalEdit'),
                Forms\Components\TextInput::make('BuatOleh')
                    ->maxLength(255),
                Forms\Components\TextInput::make('EditOleh')
                    ->maxLength(255),
                Forms\Components\TextInput::make('BulanKumulatif')
                    ->numeric(),
                Forms\Components\TextInput::make('TotalBulan')
                    ->numeric(),
                Forms\Components\TextInput::make('Gapok_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('Gapok_K')
                    ->numeric(),
                Forms\Components\TextInput::make('TunKeluarga_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('TunKeluarga_K')
                    ->numeric(),
                Forms\Components\TextInput::make('TunKhusus_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('TunKhusus_K')
                    ->numeric(),
                Forms\Components\TextInput::make('TunLain_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('TunLain_K')
                    ->numeric(),
                Forms\Components\TextInput::make('SilBruto_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('SilBruto_K')
                    ->numeric(),
                Forms\Components\TextInput::make('PenBruto_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('PenBruto_K')
                    ->numeric(),
                Forms\Components\TextInput::make('BJab_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('BJab_K')
                    ->numeric(),
                Forms\Components\TextInput::make('Ipen_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('Ipen_K')
                    ->numeric(),
                Forms\Components\TextInput::make('PTKP_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('PTKP_K')
                    ->numeric(),
                Forms\Components\TextInput::make('PKP_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('PKP_K')
                    ->numeric(),
                Forms\Components\TextInput::make('PPHTerhutang_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('PPHTerhutang_K')
                    ->numeric(),
                Forms\Components\TextInput::make('PPHSetor_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('PPHSetor_K')
                    ->numeric(),
                Forms\Components\TextInput::make('SilTakTeratur_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('SilTakTeratur_K')
                    ->numeric(),
                Forms\Components\TextInput::make('PPHTakTeratur_KL')
                    ->numeric(),
                Forms\Components\TextInput::make('PPHTakTeratur_K')
                    ->numeric(),
                Forms\Components\TextInput::make('StIrja')
                    ->numeric(),
                Forms\Components\TextInput::make('GapokLama')
                    ->maxLength(255),
                Forms\Components\TextInput::make('Kd_pkt_gol')
                    ->numeric(),
                Forms\Components\TextInput::make('Gapok')
                    ->maxLength(255),
                Forms\Components\TextInput::make('TGrade')
                    ->numeric(),
                Forms\Components\TextInput::make('Tperbatasan')
                    ->numeric(),
                Forms\Components\TextInput::make('TWP')
                    ->numeric(),
                Forms\Components\TextInput::make('KdSatker')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KdAnakSatker')
                    ->maxLength(255),
                Forms\Components\TextInput::make('MKG')
                    ->maxLength(255),
                Forms\Components\TextInput::make('NPWP')
                    ->maxLength(255),
                Forms\Components\TextInput::make('NAMA_REK')
                    ->maxLength(255),
                Forms\Components\TextInput::make('NAMA_BANK')
                    ->maxLength(255),
                Forms\Components\TextInput::make('NO_REK')
                    ->maxLength(255),
                Forms\Components\TextInput::make('SANDI')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_BANK_SPAN')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_SWIFT')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_POS')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_NEGARA')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_KPPN')
                    ->maxLength(255),
                Forms\Components\TextInput::make('TIPE_SUP')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KOTA')
                    ->maxLength(255),
                Forms\Components\TextInput::make('PROV')
                    ->maxLength(255),
                Forms\Components\TextInput::make('EMAIL')
                    ->maxLength(255),
                Forms\Components\TextInput::make('TELEPON')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_IBAN')
                    ->maxLength(255),
                Forms\Components\TextInput::make('ALAMAT')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_NAB')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_LOKASI')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KD_KABKOTA')
                    ->maxLength(255),
                Forms\Components\TextInput::make('NRS')
                    ->maxLength(255),
                Forms\Components\TextInput::make('KDJAB')
                    ->maxLength(255),
                Forms\Components\TextInput::make('NRP_FULL')
                    ->maxLength(255),
                Forms\Components\TextInput::make('TEMPATLHR')
                    ->maxLength(255),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->headerActions([
                ExportAction::make()
                    ->exporter(DataPokokExporter::class)
            ])
            ->columns([
                Tables\Columns\TextColumn::make('NRP')
                    ->label('NRP')
                    ->searchable(),
                Tables\Columns\TextColumn::make('Nama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('Pangkat')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PangkatTituler')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KelompokDPP')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('AsalMasukan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TMTTNI')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TMTPenyesuaian')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SatJuruBayar')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TanggalLahir')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('JenisKelamin')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('StatusKawin')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('JumlahAnak')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('JumlahTanggungan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('StatPenghasilan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Korps')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('UnitOrganisasi')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Kotama')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('StatJabatan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('JenisJabatan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('EselonJabatan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('JnsJab2')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('EseJab2')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('NamaJabatan')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TMTJabatan')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Skorsing')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Kotji')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('GantiRugi')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SewaRumah')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunPeralihan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('BulanWarakawuri')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SatOrganik')
                    ->searchable(),
                Tables\Columns\TextColumn::make('Pekas')
                    ->searchable(),
                Tables\Columns\TextColumn::make('Satker')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TanggalBuat')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TanggalEdit')
                    ->dateTime()
                    ->sortable(),
                Tables\Columns\TextColumn::make('BuatOleh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('EditOleh')
                    ->searchable(),
                Tables\Columns\TextColumn::make('BulanKumulatif')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TotalBulan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Gapok_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Gapok_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunKeluarga_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunKeluarga_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunKhusus_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunKhusus_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunLain_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TunLain_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SilBruto_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SilBruto_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PenBruto_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PenBruto_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('BJab_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('BJab_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Ipen_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Ipen_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PTKP_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PTKP_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PKP_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PKP_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PPHTerhutang_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PPHTerhutang_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PPHSetor_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PPHSetor_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SilTakTeratur_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('SilTakTeratur_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PPHTakTeratur_KL')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('PPHTakTeratur_K')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('StIrja')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('GapokLama')
                    ->searchable(),
                Tables\Columns\TextColumn::make('Kd_pkt_gol')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Gapok')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TGrade')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('Tperbatasan')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('TWP')
                    ->numeric()
                    ->sortable(),
                Tables\Columns\TextColumn::make('KdSatker')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KdAnakSatker')
                    ->searchable(),
                Tables\Columns\TextColumn::make('MKG')
                    ->searchable(),
                Tables\Columns\TextColumn::make('NPWP')
                    ->searchable(),
                Tables\Columns\TextColumn::make('NAMA_REK')
                    ->searchable(),
                Tables\Columns\TextColumn::make('NAMA_BANK')
                    ->searchable(),
                Tables\Columns\TextColumn::make('NO_REK')
                    ->searchable(),
                Tables\Columns\TextColumn::make('SANDI')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_BANK_SPAN')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_SWIFT')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_POS')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_NEGARA')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_KPPN')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TIPE_SUP')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KOTA')
                    ->searchable(),
                Tables\Columns\TextColumn::make('PROV')
                    ->searchable(),
                Tables\Columns\TextColumn::make('EMAIL')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TELEPON')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_IBAN')
                    ->searchable(),
                Tables\Columns\TextColumn::make('ALAMAT')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_NAB')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_LOKASI')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KD_KABKOTA')
                    ->searchable(),
                Tables\Columns\TextColumn::make('NRS')
                    ->searchable(),
                Tables\Columns\TextColumn::make('KDJAB')
                    ->searchable(),
                Tables\Columns\TextColumn::make('NRP_FULL')
                    ->searchable(),
                Tables\Columns\TextColumn::make('TEMPATLHR')
                    ->searchable(),
                Tables\Columns\TextColumn::make('created_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
                Tables\Columns\TextColumn::make('updated_at')
                    ->dateTime()
                    ->sortable()
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make(),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getRelations(): array
    {
        return [
            //
        ];
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListDataPokoks::route('/'),
            'create' => Pages\CreateDataPokok::route('/create'),
            'view' => Pages\ViewDataPokok::route('/{record}'),
            'edit' => Pages\EditDataPokok::route('/{record}/edit'),
        ];
    }
}
